In [1]:
import numpy as np

In [8]:
a = np.array([100,101,102,103])
a

array([100, 101, 102, 103])

In [13]:
c = np.arange(1.5,10,.5)
c

array([1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5,
       8. , 8.5, 9. , 9.5])

In [16]:
d = np.linspace(1.5,9,10)
d

array([1.5       , 2.33333333, 3.16666667, 4.        , 4.83333333,
       5.66666667, 6.5       , 7.33333333, 8.16666667, 9.        ])

In [17]:
d -1

array([0.5       , 1.33333333, 2.16666667, 3.        , 3.83333333,
       4.66666667, 5.5       , 6.33333333, 7.16666667, 8.        ])

In [18]:
d*2

array([ 3.        ,  4.66666667,  6.33333333,  8.        ,  9.66666667,
       11.33333333, 13.        , 14.66666667, 16.33333333, 18.        ])

In [2]:
np.random.seed(42)

In [3]:
np.random.randint(1,10,5)

array([7, 4, 8, 5, 7])

In [4]:
np.random.random_sample(10)

array([4.45832753e-01, 9.99749158e-02, 4.59248892e-01, 3.33708611e-01,
       1.42866818e-01, 6.50888473e-01, 5.64115790e-02, 7.21998772e-01,
       9.38552709e-01, 7.78765841e-04])

#### Random samples from normal distribution with (mean, std.dev)

In [5]:
np.random.normal(loc=5.3,scale=1.2,size=10)

array([5.32666619, 4.7866485 , 4.66181911, 5.1590294 , 5.56649468,
       4.3784282 , 5.47095752, 5.25841738, 6.66120712, 5.17430534])

In [8]:
mean = 5.3
stddev = 1.2
size = 10
mean + stddev * np.random.randn(size)

array([7.59532553, 2.86793646, 6.64330833, 6.23503116, 3.97868269,
       6.65627383, 5.7477427 , 4.83623246, 3.90947571, 5.97933539])